version: '3'
services:
  springboot-docker-compose-app-container:
    image:springboot-dockercompose-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - data/springboot-dockercompose-app
    ports:
      - "8080:8080"
